use crate::prelude::*;

/// Build the generic params, parent type, and where-clause fragment for a
/// resolver function's parent argument. With a parent model name, the parent
/// is that concrete gql type. Without one, the parent is generic over any
/// GqlModel, inferred from the call site (e.g. self in the relation body).
/// The generic params fragment has no leading/trailing comma, callers splice
/// it into their own generic param list (a trailing comma there is fine).
pub fn parent_ty_parts(parent: Option<&String>) -> SynRes<(Ts2, Ts2, Ts2)> {
    let r = match parent {
        Some(p) => {
            let ty = ty_gql(p)?;
            (quote!(), quote!(#ty), quote!())
        }
        None => (
            quote!(P, E),
            quote!(P),
            quote! {
                E: EntityX<G = P>,
                P: GqlModel<E>,
            },
        ),
    };
    Ok(r)
}

/// Reject an fn signature with declared inputs - many_resolver/count_resolver/one_resolver/
/// field_resolver generate the full parameter list (parent, ctx, tx) themselves, so the user
/// fn should take none.
pub fn ensure_no_inputs(sig: &Signature) -> SynRes<()> {
    if sig.inputs.is_empty() {
        return Ok(());
    }
    let msg = "should take no inputs, parent/ctx/tx are auto injected by the macro";
    Err(SynErr::new(sig.inputs.span(), msg))
}

/// Reject an fn signature with a declared output type - many_resolver/count_resolver/one_resolver
/// generate the return type themselves (Res<Search<..>> / Res<Count> / Res<Detail>).
pub fn ensure_no_output(sig: &Signature) -> SynRes<()> {
    match &sig.output {
        ReturnType::Default => Ok(()),
        ReturnType::Type(_, ty) => {
            let msg = "should not declare an output type, it is generated by the macro";
            Err(SynErr::new(ty.span(), msg))
        }
    }
}
